'use client';

import { AnimatePresence, motion } from 'motion/react';
import { useId, useState } from 'react';
import { cn } from '@/lib/cn';
import { collapse } from '@/lib/motion';

interface TextFieldProps extends React.ComponentPropsWithoutRef<'input'> {
  label: string;
  error?: string;
  hint?: string;
  /** Adds a show/hide control. Use for password inputs. */
  revealable?: boolean;
  /** Rendered inside the field, right-aligned — e.g. a "Forgot?" link. */
  action?: React.ReactNode;
}

export function TextField({
  id: idProp,
  label,
  error,
  hint,
  revealable = false,
  action,
  className,
  type = 'text',
  ...props
}: TextFieldProps) {
  // Self-generated by default so the label is always wired up, but callers may
  // supply a stable id when they need to target the field — moving focus to the
  // first invalid input on submit, for instance.
  const generatedId = useId();
  const id = idProp ?? generatedId;
  const errorId = `${id}-error`;
  const hintId = `${id}-hint`;
  const [revealed, setRevealed] = useState(false);

  const resolvedType = revealable ? (revealed ? 'text' : 'password') : type;

  return (
    <div className="w-full">
      <div className="mb-1.5 flex items-baseline justify-between gap-3">
        <label htmlFor={id} className="text-xs font-medium text-text-muted">
          {label}
        </label>
        {action}
      </div>

      <div className="relative">
        <input
          id={id}
          type={resolvedType}
          // Point at the error when present, the hint otherwise — announcing a
          // stale hint alongside a live error is more confusing than silence.
          aria-invalid={error ? true : undefined}
          aria-describedby={error ? errorId : hint ? hintId : undefined}
          className={cn(
            'peer w-full rounded-lg border bg-surface-inset px-3.5 text-base text-text',
            'h-11 outline-none',
            'transition-[border-color,box-shadow,background-color] duration-fast ease-out-quint',
            'hover:border-border-strong',
            'focus:border-accent focus:bg-surface focus:shadow-[0_0_0_3px_var(--color-accent-subtle)]',
            // The focus ring above is the visible affordance; the global
            // outline would double up on it.
            'focus-visible:outline-none',
            error
              ? 'border-danger-border focus:border-danger focus:shadow-[0_0_0_3px_var(--color-danger-subtle)]'
              : 'border-border',
            revealable && 'pr-11',
            className,
          )}
          {...props}
        />

        {revealable && (
          <button
            type="button"
            onClick={() => setRevealed((v) => !v)}
            // Sits inside the field; label it so it is not announced as an
            // unnamed button between the input and the next control.
            aria-label={revealed ? 'Hide password' : 'Show password'}
            aria-pressed={revealed}
            className={cn(
              'absolute top-1/2 right-1 -translate-y-1/2 rounded-md p-2',
              'text-text-subtle transition-colors duration-fast',
              'hover:text-text focus-visible:text-text',
            )}
          >
            <svg viewBox="0 0 20 20" className="size-4" fill="none" aria-hidden="true">
              <path
                d="M2 10s3-5.5 8-5.5S18 10 18 10s-3 5.5-8 5.5S2 10 2 10Z"
                stroke="currentColor"
                strokeWidth="1.5"
              />
              <circle cx="10" cy="10" r="2.25" stroke="currentColor" strokeWidth="1.5" />
              {revealed && (
                <path
                  d="M4 16L16 4"
                  stroke="currentColor"
                  strokeWidth="1.5"
                  strokeLinecap="round"
                />
              )}
            </svg>
          </button>
        )}
      </div>

      {hint && !error && (
        <p id={hintId} className="mt-1.5 text-xs text-text-subtle">
          {hint}
        </p>
      )}

      <AnimatePresence initial={false}>
        {error && (
          <motion.p
            id={errorId}
            // polite, not assertive: the message is already tied to the field
            // via aria-describedby, and assertive would interrupt mid-typing.
            role="status"
            variants={collapse}
            initial="hidden"
            animate="visible"
            exit="exit"
            className="flex items-start gap-1.5 overflow-hidden text-xs text-danger"
          >
            <svg viewBox="0 0 16 16" className="mt-px size-3.5 shrink-0" aria-hidden="true">
              <circle cx="8" cy="8" r="6.5" stroke="currentColor" strokeWidth="1.5" fill="none" />
              <path
                d="M8 4.75v3.75"
                stroke="currentColor"
                strokeWidth="1.5"
                strokeLinecap="round"
              />
              <circle cx="8" cy="11.25" r="0.85" fill="currentColor" />
            </svg>
            {error}
          </motion.p>
        )}
      </AnimatePresence>
    </div>
  );
}
