import type { Readable } from 'node:stream';
import { Injectable, Logger, OnModuleInit, ServiceUnavailableException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { Client } from 'minio';
import { ERROR_CODES, apiError } from '../common/errors/error-codes';
import type { Env } from '../config/env.validation';

/**
 * The object store. Bytes live here; PostgreSQL holds only the key.
 *
 * Every method takes a key produced by `buildStorageKey` — no method accepts a
 * key from a request. That is the whole tenant boundary at this layer: the
 * guard cannot help here, because MinIO has no idea what a company is.
 */
@Injectable()
export class StorageService implements OnModuleInit {
  private readonly logger = new Logger(StorageService.name);
  private readonly client: Client;

  readonly bucket: string;

  constructor(config: ConfigService<Env, true>) {
    this.bucket = config.get('MINIO_BUCKET', { infer: true });

    this.client = new Client({
      endPoint: config.get('MINIO_ENDPOINT', { infer: true }),
      port: config.get('MINIO_PORT', { infer: true }),
      useSSL: config.get('MINIO_USE_SSL', { infer: true }),
      accessKey: config.get('MINIO_ACCESS_KEY', { infer: true }),
      secretKey: config.get('MINIO_SECRET_KEY', { infer: true }),
    });
  }

  /**
   * Ensures the bucket exists.
   *
   * docker-compose runs a `minio-init` job that creates it with versioning
   * enabled, but that is a dev-only sidecar and the API must not depend on
   * something outside its own deployment having run.
   *
   * A failure here is logged rather than thrown. Unlike bad configuration —
   * which fails the process at boot on purpose — a storage outage is transient,
   * and crash-looping the whole API would take auth and /health down with it.
   * Uploads fail individually with STORAGE_UNAVAILABLE instead, which points at
   * the actual problem.
   */
  async onModuleInit(): Promise<void> {
    try {
      if (await this.client.bucketExists(this.bucket)) {
        return;
      }

      await this.client.makeBucket(this.bucket);
      this.logger.log(`Created object storage bucket "${this.bucket}"`);
    } catch (error) {
      this.logger.error(
        `Object storage is unreachable at startup; uploads and downloads will fail until it recovers`,
        error,
      );
    }
  }

  /** Uploads a file from disk. Used by the upload pipeline's temp file. */
  async putFile(key: string, filePath: string, mimeType: string): Promise<void> {
    try {
      await this.client.fPutObject(this.bucket, key, filePath, { 'Content-Type': mimeType });
    } catch (error) {
      this.logger.error(`Failed to store object ${key}`, error);
      throw new ServiceUnavailableException(
        apiError(ERROR_CODES.STORAGE_UNAVAILABLE, 'The file could not be stored. Try again.'),
      );
    }
  }

  /** Opens a read stream, for streaming a download straight through the API. */
  async getStream(key: string): Promise<Readable> {
    try {
      return await this.client.getObject(this.bucket, key);
    } catch (error) {
      this.logger.error(`Failed to read object ${key}`, error);
      throw new ServiceUnavailableException(
        apiError(ERROR_CODES.STORAGE_UNAVAILABLE, 'The file could not be read. Try again.'),
      );
    }
  }

  /**
   * Reads an entire object into memory.
   *
   * For the processing pipeline only, which genuinely needs the whole file at
   * once: a PDF cannot be parsed from a partial stream, and OCR needs every
   * page. Downloads deliberately do NOT use this — they stream, so a 100 MB
   * file costs a constant amount of memory per request rather than 100 MB.
   *
   * The ceiling is MAX_FILE_SIZE (100 MB by default) times QUEUE_CONCURRENCY
   * (2), which is why that concurrency is low and configurable.
   */
  async getBuffer(key: string): Promise<Buffer> {
    const stream = await this.getStream(key);
    const chunks: Buffer[] = [];

    for await (const chunk of stream) {
      chunks.push(chunk as Buffer);
    }

    return Buffer.concat(chunks);
  }

  /**
   * Stores generated bytes — OCR page images, thumbnails.
   *
   * Separate from putFile() because derived artifacts are produced in memory
   * rather than landing on disk as a multer temp file first.
   */
  async putBuffer(key: string, body: Buffer, mimeType: string): Promise<void> {
    try {
      await this.client.putObject(this.bucket, key, body, body.length, {
        'Content-Type': mimeType,
      });
    } catch (error) {
      this.logger.error(`Failed to store object ${key}`, error);
      throw new ServiceUnavailableException(
        apiError(ERROR_CODES.STORAGE_UNAVAILABLE, 'The file could not be stored. Try again.'),
      );
    }
  }

  /**
   * Server-side copy of one stored object to a new key.
   *
   * Reverting a document to an earlier version needs the old bytes under a NEW
   * key, because `document_versions.storage_key` is unique — two rows cannot
   * name one object, and history is append-only, so a revert appends a version
   * rather than re-pointing at an old one.
   *
   * Copied inside MinIO rather than streamed down and back up: the bytes never
   * enter this process, so reverting a 100 MB scan costs no memory here.
   *
   * Both keys are derived server-side by `buildStorageKey`, never supplied by a
   * client — this is a path, and accepting one from a request would be a way to
   * read or write across tenant prefixes.
   */
  async copyObject(sourceKey: string, destinationKey: string): Promise<void> {
    try {
      await this.client.copyObject(this.bucket, destinationKey, `/${this.bucket}/${sourceKey}`);
    } catch (error) {
      this.logger.error(`Failed to copy object ${sourceKey} to ${destinationKey}`, error);
      throw new ServiceUnavailableException(
        apiError(ERROR_CODES.STORAGE_UNAVAILABLE, 'The file could not be copied. Try again.'),
      );
    }
  }

  /**
   * Deletes an object, swallowing failure.
   *
   * Only for unwinding a half-finished upload. The database row is the source
   * of truth, so an object left behind is wasted space rather than a
   * correctness problem — and throwing here would replace the error the caller
   * is already reporting with a less useful one.
   */
  async removeQuietly(key: string): Promise<void> {
    try {
      await this.client.removeObject(this.bucket, key);
    } catch (error) {
      this.logger.warn(`Could not clean up orphaned object ${key}`, error);
    }
  }
}
